### ISSUE TITLE
[HeartBeat] Skip heartbeat bytes

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere-javascript#122]
Related to Atmosphere/atmosphere#1736

The heartbeat value must not be delivered to the onMessage callback.

**Comment by reda-alaoui** [comment]
Hi Jean-François,
Your correction is valid when ```request.enableProtocol === true```.
Otherwise ```onmessage``` is called with the message ```X```.

Am I wrong?

**Comment by jfarcand** [comment]
@reda-alaoui Contribution welcomed :-) Write a test case that demonstrate the issue as I have very limited time those days.
