### ISSUE TITLE
No reopen callback is fired when a heartbeat closes the connection (long polling)

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere-javascript#141]
When the server has heartbeat enabled (as Atmosphere 2.2 has by default) the server will ping the client after 60s idle time. The client will at this point re-connect and fire an onReconnecting event BUT when the reconnect is complete, there is no onReopen event fired. This means that anybody listening to the events will keep listening for an event that indicates when the connection is up again until sending the next message (it will wait forever as there is no such event fired)

**Comment by ookke** [comment]
We also encountered this, I think it has something to do with this IE specific (?) check that is always executed:
https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/javascript/src/main/webapp/javascript/atmosphere.js#L1995

As a workaround changing the default server heartbeat padding from whitespace to something else seems to help.

**Comment by jfarcand** [comment]
@ookke This has been changed in 2.3.0 BTW.

**Comment by Artur-** [comment]
@jfarcand Does that mean that onReopen is fired as expected in 2.3?

**Comment by jfarcand** [comment]
@Artur- Yes, it should. I will close the issue once I've a chance to test it. But for sure in 2.3 the padding bytes is set to `x`.

**Comment by peholmst** [comment]
Is this ticket still valid or has it been fixed?

**Comment by jfarcand** [comment]
@peholmst Not sure to be honest, but no time to test it.
