### ISSUE TITLE
jquery.atmosphere-min.js contains lot of security bridges.

### ISSUE THREAD

**Issue by Vitalidov** [Atmosphere/atmosphere-javascript#145]
Hello, 

Our security test found following: 

1. The file jquery.atmosphere-min.js interprets unvalidated user input as source code on line 482. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

2. The file jquery.atmosphere-min.js interprets unvalidated user input as source code on line 522. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

3. The file jquery.atmosphere-min.js interprets unvalidated user input as source code on line 534. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

4. The file jquery.atmosphere-min.js interprets unvalidated user input as source code on line 553. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

5.The file jquery.atmosphere-min.js interprets unvalidated user input as source code on line 587. Interpreting user-controlled instructions at run-time can allow attackers to execute malicious code.

Could you review and provide mitigation/hardening guide please?

BR

**Comment by jfarcand** [comment]
Which version are you using? Also please run your test on the jquery.atmosphere.js. not the minified one. Also can you clarify the `unvalidated user input` statement and how it can be maliciously used?

**Comment by Vitalidov** [comment]
Hi,

In js file, I can see following version: "2.0.0-jquery"

Unfortunately, I receive the report from PenLabs (they run the test on our
staging) and I cannot rerun it using  jquery.atmosphere.js.

The general problem in all points - assign responseText to localScope
variable without perform input validation.

Could you check it please?

BR

**Comment by jfarcand** [comment]
Please use the latest release which is 2.2.6. Also since the `responseText` is from your own server, I don't see how this can be a security issue. Do the validation server side instead. If you need more information, I recommend you buy some support with [Async-IO.org](http://async-io.org/subscription.html). Closing as not a bug.
