### ISSUE TITLE
404 response to long-polling reconnect request calls onReopen

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere-javascript#163]
If the reconnect request for long-polling (maybe also for other transports) encounters a 404, Atmosphere (JQuery version) will incorrectly call onReopen and a short while later call onReconnect. The onReopen call comes from https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/jquery/src/main/webapp/jquery/jquery.atmosphere.js#L1891 when readyState becomes 2 and we are not waiting for the first message

**Comment by Artur-** [comment]
This was encountered when re-starting a server which was behind a proxy, causing the proxy to send 404 to the client while the server was restarting

**Comment by jfarcand** [comment]
So what would you like to happen? It will call `onError` after couple of retry. Can you paste the log here in case it doesn't?

**Comment by jfarcand** [comment]
@Artur- Any update?

**Comment by Artur-** [comment]
I was looking for a way to handle all status codes other than 200 myself, but it's no longer an issue for us as we already moved to doing a separate xhr outside Atmosphere and are that way able to handle all error cases
