### ISSUE TITLE
npm package for the browser client

### ISSUE THREAD

**Issue by jonrimmer** [Atmosphere/atmosphere-javascript#164]
It's increasingly common to use npm to manage front-end dependencies, as part of using tools like [Browserify](http://browserify.org/) and [Webpack](http://webpack.github.io/). It would be great if there was an npm package containing the Atmosphere browser client to enable this.

**Comment by elakito** [comment]
atmosphere.js is available at npm.
https://www.npmjs.com/package/atmosphere.js

So, I don't know if you were looking for this or something else?

**Comment by JonRimmer** [comment]
Ah, I did see that, but from the description I thought it specialised for use in Node only. Never mind then.

**Comment by jonrimmer** [comment]
I have tried using that repo, but unfortunately it introduces a variety of node-specific dependencies that end up requiring gcc installed on the build machine. Also, the ergonomics of using it aren't great, because the index.js is intended for node, not for browser use.

It would be very handy to have an npm repo that just contains the browser client, not a version of the browser client adapter for use in node.

**Comment by elakito** [comment]
@jonrimmer 
okay. I'll look into it.

**Comment by flowersinthesand** [comment]
@elakito I've never used Browserify but saw [a note for browserify users](https://github.com/websockets/ws#browserify-users) to work around similar problem from https://github.com/websockets/ws

It seems that [`browser` field in package.json](https://github.com/websockets/ws/blob/62c154c7ba97eaf6ac346f855af956c8b96f0ead/package.json#L39) and [browser.js](https://github.com/websockets/ws/blob/f429240aea5c2f49f77d29003681b5c352bbe263/lib/browser.js) make it possible. Take a look.

**Comment by elakito** [comment]
@flowersinthesand 
thanks. I'll go through the information.

**Comment by elakito** [comment]
@flowersinthesand 
i spent some time to understand the problem but I am still missing something fundamental.
If I understand it, the browser.js example does a short cut to use Browser's WebSocket and it is there so it can do the module.exports from there.
For atmosphere, how does this mechanism apply? if we use a similar js file as the entry point, how can we do the module.exports for the atmosphere from there?

Another thing that came to my mind while looking at the dependency of atmosphere.js to those window's objects, could we remove them (if not present)? So we have only ws dependency?
regards, aki

**Comment by flowersinthesand** [comment]
@elakito I'm sorry but haven't had time to investigate that unfortunately. You had better get help from http://browserify.org/ For such issues including dependency, I used [UMD pattern](https://github.com/umdjs/umd) but not sure it works with Browserify.

@jonrimmer Do you have any idea on this as a Browserify user?

**Comment by elakito** [comment]
@flowersinthesand I played around with your suggestion of the global pattern and I got some idea but I don't know if this is what @jonrimmer  et al want.

What we can do is to add module.exports in atmosphere.js to handle the CommonJS case and change index.js to use the global pattern to instantiate the window object et al and loads this atmosphere.js script instead of using fs and window.eval to load the script as it is done now. Then we can also add its browser.js version that simply loads the atmosphere.js script. Browserify seems to work in this case.

**Comment by jonrimmer** [comment]
@elakito That sounds good. So long as I can ```import atmosphere from 'atmosphere'``` I'll be OK. That said, it would be nice to have a browser-only npm package without the additional node-only dependencies, particularly on jsdom, as it's a bit annoying to have a GCC compilation step in there.

**Comment by elakito** [comment]
@jonrimmer the updated npm package is available at git-repo https://github.com/Atmosphere/atmosphere.js-node
This package hasn't been uploaded to npm. So, I am wondering if you can use this local version in your setup to see if this is working for you. If you can verify it, that would be appreciated.
thanks.
regards, aki

**Comment by elakito** [comment]
I'm closing this ticket for now as the newly released atmosphere.js 2.2.12 version includes the change that was made with this ticket. In this way, we can tag this ticket with 2.2.12.
thanks.
regards, aki

**Comment by jonrimmer** [comment]
@elakito We've tried using this version, unfortunately the (unnecessary, for the browser) dependency on jsdom is causing build problems. The version you depend on is very old (circa 2013) and will not install using node.js 4 and above.

**Comment by jfarcand** [comment]
@jonrimmer Pull request welcomed :-)

**Comment by flowersinthesand** [comment]
@jonrimmer With `process.version`, you can determine which version of Node you are using and load the corresponding jsdom dependency dynamically. See https://github.com/jquery/jquery/commit/dbb2daa8c3a458e3525d310440f4365548edc138 for details.

**Comment by elakito** [comment]
@jonrimmer I hoped the browser attribute that we use would let you use the atmosphere library without picking up the unnecessary jsdom et al because browser.js is not. But it seems it gets loaded as it is still included in the dependencies section.

For jsdon, if I remember correctly, this was used only to get the windows object and subsequently some attributes from it. So we could possibly eliminate the use of jsdom completely by supplying these attributes directly. @flowersinthesand Maybe would this be a simpler approach? But I am currently traveling and can't look at it in details now.

regards, aki

**Comment by jonrimmer** [comment]
@jfarcand @flowersinthesand It's difficult for me to make a pull request fixing this given that I do not use the library in a node project, so I could easily end up breaking something for those that do.

**Comment by elakito** [comment]
hi @jonrimmer @jfarcand @flowersinthesand 
I looked into the idea that I described some weeks ago.

It seems atmosphere.js is working without jsdom at leat for a simple node client scenario (atmosphere's samples/chat-node-client) against samples/websocket-chat.

I'll play around a little more today to see if everything is fine.
regards, aki

**Comment by elakito** [comment]
I committed the change to atmosphere.js-node (see the referred issue above).

@jonrimmer could you try out this version locally before we upload this to the npm repo?
if this version works, we will need to release atmosphere.js 2.2.13 and update the npm repo.

regards, aki

**Comment by jfarcand** [comment]
@elakito Thanks for the work!

**Comment by jonrimmer** [comment]
@elakito It works! :+1:

**Comment by elakito** [comment]
@jonrimmer thanks for your feedback.
