### ISSUE TITLE
XDR doesn't fail with polling

### ISSUE THREAD

**Issue by 40rn05lyv** [Atmosphere/atmosphere-javascript#168]
I have a case - IE7 + streaming.

atmosphere.js fails to perform xdr request (xdr.onerror (line 2262) is executed). Comment in that method states: " // If the server doesn't send anything back to XDR will fail with polling", but it doesn't.

I even tried to force it to fall with polling:
    rq.transport = 'polling'

However, it doesn't make sense, because after that `function _ieXDR(request)` is executed:

```
            if (request.transport !== "polling") {
                _ieStream = _configureXDR(request);
                _ieStream.open();
            } else {
                _configureXDR(request).open();
            }
```

As you can see from code, there is no difference between polling and not polling - code is exactly the same. Therefore, browser executes xdr.onerror (line 2262) again and again.

**Comment by jfarcand** [comment]
@40rn05lyv The comment is wrong as `polling` is not supported at all with `atmosphere.js`. For IE 7, use `jsonp` instead.

**Comment by 40rn05lyv** [comment]
Ok. What about setting jsonp as request.transport after XDR fail?

As I understand XDR fails only if cross-origin requests are not enabled in browser, so reconnecting with the same parameters doesn't make sense.

**Comment by jfarcand** [comment]
@40rn05lyv Does `onTransportFailiure` invoked or just `onError`? You could try it inside that callback to set the `fallbackTransport`. I can't test it so if you have the cycle contribution welcomed!
