### ISSUE TITLE
Client sends "zeros" to the server.

### ISSUE THREAD

**Issue by CPBach** [Atmosphere/atmosphere-javascript#170]
Hi,

i've created a new repository for this issue(?) which replicates the bug: https://github.com/CPBach/Atmosphere-RepeatedZerosBug

I'm using atmosphere-js on client-side with dropwizard(jetty) on server-side.
When connecting to server, the client sometimes sends a lot of '0' to the server.
I'm not sure, maybe I misconfigured something.
![atmospherebug](https://cloud.githubusercontent.com/assets/10188734/8851862/38363cc2-3152-11e5-90ec-751f937a8429.png)

**Comment by jfarcand** [comment]
Please use the mailing list for question: https://groups.google.com/group/atmosphere-framework?pli=1
