### ISSUE TITLE
Offline/Online event is not getting trigger in Firefox

### ISSUE THREAD

**Issue by adityaba** [Atmosphere/atmosphere-javascript#173]
To regenerate: Open websocket using atmosphere.js (2.2.11v) and unplug LAN cable or switch off WIFI.

**Comment by elakito** [comment]
@adityaba i don't think firefox interprets this condition (i.e., no-cable or network turned-off) as offline.
firefox triggers the offline event when its WorkOffline menu is selected.
https://bugzilla.mozilla.org/show_bug.cgi?id=654579
