### ISSUE TITLE
onOpen not fired using websocket when enableProtocol = true

### ISSUE THREAD

**Issue by gualtierotesta** [Atmosphere/atmosphere-javascript#174]
**onOpen event is not fired** when websocket connection is established if request.enableProtocol = true (which is the default for the Chat sample application).

Browser console shows:

```
Invoking executeWebSocket, using URL: ws://localhost:8080/atmosphere-chat/chat?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.13-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json&X-atmo-protocol=true

Tue Sep 08 2015 10:43:28 GMT+0200 (ora legale Europa occidentale) Atmosphere: websocket.onopen

Websocket successfully opened
```
but the onOpen event is not fired and the text field in the chat page remains disabled.

When enableProtocol = false, the browser console shows:

```
Invoking executeWebSocket, using URL: ws://localhost:8080/atmosphere-chat/chat?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.2.13-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json

Tue Sep 08 2015 10:46:52 GMT+0200 (ora legale Europa occidentale) Atmosphere: websocket.onopen

Websocket successfully opened

Tue Sep 08 2015 10:46:52 GMT+0200 (ora legale Europa occidentale) Atmosphere: Firing onOpen
```

When protocol is set to **long-polling**, onOpen event is always *fired*.

I think line 1412 in atmosphere.js is the cause of the problem: **webSocketOpened** variable is set to true only if enableProtocol is false.

**Environment:**
- Chat sample (latest commit 3ccb0d24b5 )
- Atmosphere.js  2.2.13
- Atmosphere Runtime 3.0.0-SNAPSHOT
- Tomcat 8.0.23
- Oracle JDK 7u80 
- Windows 7
- Firefox 40
- IE 11
- Chrome 45

**Comment by jfarcand** [comment]
@gualtierotesta Something is broken in your environement (see the screen below). Using the atmosphere-chat-3.0.0-SNAPSHOT latest every thing works as expected. You may have a proxy or firewal blocking the bytes.

<img width="1060" alt="screen shot 2015-09-08 at 8 03 24 am" src="https://cloud.githubusercontent.com/assets/51285/9734344/2f025230-5600-11e5-88df-f5a908522a35.png">

**Comment by gualtierotesta** [comment]
uhm. let me add a couple of comments:

1) I don't think I have proxy/firewall issues as I'm working locally and chat sample works when protocol is "long-polling" and when protocol is "websocket" and enableProtocol=false.

2) Your picture shows that `websocket.onopen()` is invoked. This is correct. But I was refering to another function : `AtmosphereRequest.onOpen()`. It is the last one which is not invoked

Let me explain using the Chat sample application:
- The file **application.js** define the request object with an onOpen function and pass it to the Atmosphere *subscribe* function
- Atmosphere (**atmosphere.js**) performs all required initialization and finally calls the `websocket.onopen`.
- Then `websocket.onopen` calls `_open` which calls `_incokeCallback` which calls `invokeFunction` which calls `_f` which finally fires the `request.onOpen` at line 2772.

Unfortunately all this calls chain is done only ` if (!_request.enableProtocol) {` (line 1419).

From my point of view, the chat sample application cannot work if protocol is websocket and enableProtocol is true.

Can you confirm the chat application is really working at your side ? Is the input field on the chat page enabled (it is enabled by the `request.onOpen` function). Do you have the line 'Firinf onOpen' in your browser console ?

**Comment by jfarcand** [comment]
@gualtierotesta Chat applicaiton is just working fine and `onOpen` always called. So not sure where is your issue. If you can package a simple test that demonstrate the issue, that's the only way I can help.

**Comment by jfarcand** [comment]
Also if you have disbaled the [Atmosphere Protocol](https://github.com/Atmosphere/atmosphere/wiki/Understanding-the-Atmosphere-Protocol) on the server side, that's the reason why the client is not working. The `onOpen` will be called once the Atmosphere's handshake happens (so the flow you describe above is wring). Look inside [_handleProtocol](https://goo.gl/9gdfK7) method.

**Comment by gualtierotesta** [comment]
@jfarcand  I did not change anything. I have repeated again from scratch this morning:
```
git clone https://github.com/Atmosphere/atmosphere-samples.git
git show
  commit 3ccb0d24b535614aa88b935b995a73fec92da68b
  Merge: 3517371 0c3e15f
  Author: Jeanfrancois Arcand <jfarcand@apache.org>
  Date:   Fri Sep 4 09:59:12 2015 -0400
    Merge pull request #49 from manikantag/master
    Better formatted the example listing

mvn clean install
cd samples/chat
mvn jetty:run
open browser on http://localhost:8080/
```
and the situation is shown in the attached pictures.
![browser](https://cloud.githubusercontent.com/assets/4703656/9782508/ecbc60a6-579d-11e5-8d6a-99be7e7938b7.png)
![jetty_console](https://cloud.githubusercontent.com/assets/4703656/9782509/ecc09de2-579d-11e5-9d9b-ccea0afda458.png)

Thanks for your support and comments but I have no ideas for further analysis of the issue so I will stop here; my was an initial investigation about Atmosphere capabilities which are promising for us for our future applications.

Merci et bonne journée

**Comment by afxgroup** [comment]
I can confirm this. Also for my game. Without enableProtocol: true, the onOpen is never fired using websockets
