### ISSUE TITLE
Dart package

### ISSUE THREAD

**Issue by schrej** [Atmosphere/atmosphere-javascript#178]
Are there any plans regarding a dart package for atmosphere? Or does anyone know of a wrapper of the javascript version or a complete implementation of the client in dart?
In my case this would only concern the client side of atmosphere.

**Comment by jfarcand** [comment]
@schr3j I'm not aware of any, but I would be happy to help working on it.

**Comment by schr3j** [comment]
Hmmm. I just started using dart and atmosphere so i don't have any experience regarding both.
Should we rather build a wrapper arround the existing js version of atmosphere or recreate the whole client in dart?
A wrapper would be faster to develop but a complete client would be faster i guess...

**Comment by sprtnconn** [comment]
Curious if anyone's got anywhere on this?

**Comment by jfarcand** [comment]
@sprtnconn Don't think someone did it...but contribution welcomed!

**Comment by schr3j** [comment]
@sprtnconn i built a small wrapper for my personal use. It's not that great and i think it isn't even close to wrapping all the features of atmosphere but it worked quite well for me.
You can have a look [here](https://gist.github.com/schr3j/58fc8d41bfe85656a6ba9ae440e3306a).
