### ISSUE TITLE
[Chrome] Websocket reconnect fails when disconnecting network

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere-javascript#180]
1. Open atmosphere-chat with Chrome
2. Kill network connection (disable Wi-Fi or unplug Ethernet)
3. Re-enable network connection
4. App will try to reconnect with websocket but fallback to Comet

With Firefox the websocket connection is not lost (difference in onoffline handling?)

Vaadin ticket: https://dev.vaadin.com/ticket/19201

https://github.com/Atmosphere/atmosphere/issues/2082 cc @jdahlstrom

**Comment by jdahlstrom** [comment]
Thanks. I'm not sure if this is indeed a client-side issue however; it seems the client does everything by the book and it's the server than unexpectedly refuses the Websocket handshake.

**Comment by jfarcand** [comment]
Which Server are you using? Is it with jsr356 or Native? Thanks! Noet that the handshake is not handled by Atmosphere...

**Comment by jfarcand** [comment]
@jdahlstrom Also make sure you are using the latest 2.2.13.

**Comment by jdahlstrom** [comment]
Hi, sorry about the delay, had a flu plus other things on my desk. I used simply `mvn jetty:run` to run the chat server. I tried with 2.2.13 and it seems onError/onReopen aren't called anymore when the client goes offline - the chat app doesn't seem to notice that the connection was lost, but from the logs Atmosphere seems to reconnect successfully.

**Comment by elakito** [comment]
@jdahlstrom do you have this problem with atmosphere-samples/samples/chat as well using mvn jetty:run?
I don't observe this problem with 2.2.13 with the current safari and firefox on osx and chromium on ubuntu. If you see the server getting the reconnect request and this gets rejected, it doesn't look like a client issue.

**Comment by Artur-** [comment]
Related to https://github.com/Atmosphere/atmosphere-javascript/commit/28604efd8eb00a6547e360fd7332cc7c6199647e and https://github.com/Atmosphere/atmosphere-javascript/pull/187

**Comment by elakito** [comment]
I integrated #187 into atmosphere.js and ran some tests with chrome using this 2.3.1-SNAPSHOT.
it seems that it is reconnecting with websocket now.
let me know if we can close this issue or not.

**Comment by elakito** [comment]
I suppose this issue was resolved with Artur's PR, so I'm closing it.

Firefox's does its online/offline reporting differently from chrome/safari
https://bugzilla.mozilla.org/show_bug.cgi?id=654579
Unlike Chrome or Safari, Firefox seems to require the manual intervention to turn on and off the offline status.
