### ISSUE TITLE
requests is not defined

### ISSUE THREAD

**Issue by henrikekelof** [Atmosphere/atmosphere-javascript#185]
I'm getting a JavaScript error on row 75 of jquery.atmosphere.js when I go offline then online:
https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/jquery/src/main/webapp/jquery/jquery.atmosphere.js#L75

"requests is not defined"

I think `requests[i]` should be changed to `jQuery.atmosphere.requests[i]`

**Comment by elakito** [comment]
thanks.
probably something went wrong during the merge/sync from atmosphere.js.
the fix has been pushed.
