### ISSUE TITLE
Delete one of the javascript versions to improve quality

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere-javascript#188]
Having two versions and allowing/making the end user to choose might seem like a good idea but it does not seem to work out very well in practice. We recently upgraded to atmosphere-javascript 2.2.13 and it was a bad experience, just as most previous upgrades: days spent trying to figure out what has been broken and in what way.

It seems to me that people are contributing patches to the JS version they are using and then doing a quick port to the other version. I would claim that nobody actually tests the other version, the one they are not using. I for sure know that I have been doing patches this way. So per definition, a patch for the JQuery JS will break the non-JQuery JS and vice versa. 

What we found so far in jquery.atmosphere.js 2.2.13:
* https://github.com/Atmosphere/atmosphere-javascript/blob/javascript-project-2.2.13/modules/jquery/src/main/webapp/jquery/jquery.atmosphere.js#L75 uses a variable which does not exist because when copy/pasting from the non-jquery version, one instance was missed (it seems)
* https://github.com/Atmosphere/atmosphere-javascript/blob/javascript-project-2.2.13/modules/jquery/src/main/webapp/jquery/jquery.atmosphere.js#L60 the handleOnlineOffline flag is checked from the AtmosphereRequest but it's defined for the "request" object inside the AtmosphereRequest (either I misinterpret the code or this has never worked as intended)
* https://github.com/Atmosphere/atmosphere-javascript/blob/javascript-project-2.2.13/modules/jquery/src/main/webapp/jquery/jquery.atmosphere.js#L1436 reconnect attempts are always terminated for websockets if we are offline. If handleOnlineOffline is disabled, reconnect attempts will never resume. Your application is always broken if the browser goes offline.

To make this better, I would suggest wiping out, deleting, destroying either the JQuery version or the other one. Probably makes more sense to remove the JQuery version, as the other version should work just fine if you are doing a JQuery app but not vice versa. I can't imagine the size diff of 4 KB being a blocker for anyone.

With only one version:
* it becomes clear which javascript to use
* everybody will patch the same version
* most likely at least one person will have tested the code in new releases
* there is less hassle and less porting between versions

**Comment by jfarcand** [comment]
@Artur- Fully agree...I haven't maintained the jQuery one anyway. Most if not all project/sample are using the pure one. So we could deprecated the jQuery one and make it clear on the web page.

**Comment by Artur-** [comment]
Do you think it would be too radical to simply delete it and make a 2.3.0 without it? If you deprecate it, I think nobody will port any fixes/changes to it anyway

**Comment by jfarcand** [comment]
@elakito what do you think? I'm +1 for releasing 2.3.0/

**Comment by elakito** [comment]
@jfarcand, @Arthur, sounds good. Another option would be to use a template to automatically generate the jquery version from the the pure version. But just dropping the query version for 2.3.0 makes more sense. And we can rather invest the limited capacity to adding some unit tests to the project itself and to those samples in atmosphere-samples.

@jfarcand will you have time to make the change or should I do it?

**Comment by jfarcand** [comment]
@elakito Go ahead and do it once you have a chance. Thanks!

**Comment by elakito** [comment]
will take care of it.

2015-12-18 17:45 GMT+01:00 Jeanfrancois Arcand <notifications@github.com>:

**Comment by elakito** [comment]
atmosphere javascript 2.3.0 released
