### ISSUE TITLE
Browser hangs on close socket when using SSE as a transport

### ISSUE THREAD

**Issue by dmaidaniuk** [Atmosphere/atmosphere-javascript#194]
Hi,

We using Atmosphere via Prime Push (v 5.3.7) wrapper with `transport="sse"` and `fallbackTransport="long-polling"`. When using JavaScript client in both Chrome (48.0.2564) and Firefox (v44.0.2) I am experiencing the browser hanging when tried to navigate from page where socket was opened. Next request freeze a page:

```
http://localhost:8080/site/primepush/auction/update?X-Atmosphere-Transport=close&X-Atmosphere-tracking-id=d01e3e1c-c31c-44d6-a16d-d7e85e58ebe2&_=1456753291021
```

And directly after this infinite synchronous XHR the info message showed in browser log (in Firefox):

```
SSE closed normally
```

I attached to sources uncompressed `atmosphere.js` and see exactly where this hanging request was coming from:

```
_executeRequest()
_pushOnClose()
_disconnect()
_close()
close()
unsubscribe()
unload() // global eventlistener
```

Seems that problem located in wrong construction of closing request [here](https://github.com/Atmosphere/atmosphere-javascript/blob/master/modules/javascript/src/main/webapp/javascript/atmosphere.js#L2553):

```
            function _pushOnClose(message, rq) {
                if (!rq) {
                    rq = _getPushRequest(message);
                }
                rq.transport = "polling";
                rq.method = "GET";
                rq.withCredentials = false;
                rq.reconnect = false;
                rq.force = true;
                rq.suspend = false;
                rq.timeout = 1000;
                _executeRequest(rq);
            }
```

where transport is hard-coded to `"polling"`. 

Is it real source of given bug?

We used JBoss EAP 6.3 with next PushServlet config:

```
    <servlet>
        <servlet-name>Push Servlet</servlet-name>
        <servlet-class>org.primefaces.push.PushServlet</servlet-class>
        <init-param>
            <param-name>org.atmosphere.cpr.broadcasterCacheClass</param-name>
            <param-value>org.atmosphere.cache.UUIDBroadcasterCache</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.useNative</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.useWebSocket</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.useWebSocketAndServlet3</param-name>
            <param-value>false</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.annotation.packages</param-name>
            <param-value>org.primefaces.push</param-value>
        </init-param>
        <init-param>
            <param-name>org.atmosphere.cpr.packages</param-name>
            <param-value>foo.bar.push</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
        <async-supported>true</async-supported>
    </servlet>
```

Thanks,
Dmytro

**Comment by dmaidaniuk** [comment]
Same issue was reported almost 2 years ago in another sub-project: [atmosphere-extensions#136](https://github.com/Atmosphere/atmosphere-extensions/issues/136). It was closed with statement that testing build was RC. But my build isn't a release candidate and issue still present.

**Comment by ben-crowhurst** [comment]
Did we get anywhere with this issue?

**Comment by jfarcand** [comment]
@ben-crowhurst Have you try the latest release?
