### ISSUE TITLE
WebSocket close after 5 minutes when server heartbeat is disabled, even if client heartbeat is enabled due to client timeout

### ISSUE THREAD

**Issue by SuperPat45** [Atmosphere/atmosphere-javascript#195]
Using websocket transport and this configuration:

```
<init-param>
    <param-name>org.atmosphere.interceptor.HeartbeatInterceptor.clientHeartbeatFrequencyInSeconds</param-name>
    <param-value>60</param-value>
</init-param>
<init-param>
    <param-name>org.atmosphere.interceptor.HeartbeatInterceptor.heartbeatFrequencyInSeconds</param-name>
    <param-value>0</param-value>
</init-param>
```

When server heartbeat is disabled, websocket connection is disconnected with status 1001 because of client Timeout is fired after 5 minutes.
Client heartbeat is send every minutes but it does not reinitialize the client timeout.

I use this configuration to detect on server if browsers are alive.

**Comment by Talon876** [comment]
I am observing similar behavior. One thing I noticed was it seems to have the client and server config variables swapped. Or at the very least, it is displaying them incorrectly in the log: from HeartbeatInterceptor: `logger.info("HeartbeatInterceptor configured with padding value '{}', client frequency {} seconds and server frequency {} seconds", new String[]
                {new String(paddingBytes), String.valueOf(heartbeatFrequencyInSeconds), String.valueOf(clientHeartbeatFrequencyInSeconds)});`
