### ISSUE TITLE
[improvement] Consider debouncing something in interval on document view.

### ISSUE THREAD

**Issue by dariuszsikorski** [Atmosphere/atmosphere-javascript#199]
Probably there is some interval every ~200ms which freezes scrolling document for ~10ms every time.
While clicking middle mouse button and scrolling automatically it doesn't go smooth for that reason.

Example: Scrolling long document such as:
https://atmospherejs.com/aldeed/simple-schema

**Comment by jfarcand** [comment]
Wrong project ;-)
