### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by stevenjob** [Atmosphere/atmosphere-javascript#202]
Full API documentation can be read here - in the README gives a dead link.

https://github.com/Atmosphere/atmosphere/wiki/jQuery.atmosphere.js-atmosphere.js-API

Please help

**Comment by nmalfroy** [comment]
+1

**Comment by arunkjn** [comment]
Is this the correct link?https://github.com/Atmosphere/atmosphere/wiki/Understanding-JavaScript-functions

**Comment by elakito** [comment]
fixed the link at the readme page.
the correct link should be
https://github.com/Atmosphere/atmosphere/wiki/atmosphere.js-API

thanks
