### ISSUE TITLE
Make atmosphere.js more testable (PhantomJS disconnect timeout)

### ISSUE THREAD

**Issue by sbaechler** [Atmosphere/atmosphere-javascript#209]
We use atmosphere.js as a dependency in our project. On some (slower) systems and our Jenkins we get a disconnect timeout error from Phantom.js after the Jasmine tests have completed. The timeout happens on all tests that load the atmosphere javascript library.

We tracked the issue down to the `atmosphere.util.debug` call in the `beforeunload` and the `unload` callback.

Our current work-around is to overwrite `window.console.debug` with a mock function.

The unload events are bound at import time and the callback is an anonymous function. This makes it impossible to unbind. Maybe change the callbacks to named functions or use a constructor pattern.

Maybe there is also a better implementation for the log function in atmosphere.utils.

**Comment by jfarcand** [comment]
@sbaechler Contribution welcomed...no time to work on Atmosphere anymore for me, but can merge your work and cut a release

**Comment by sbaechler** [comment]
Fixed in #210. Release 2.2.3.
