### ISSUE TITLE
Remove 'use strict'

### ISSUE THREAD

**Issue by Artur-** [Atmosphere/atmosphere-javascript#213]
Reported in https://github.com/vaadin/framework/issues/8065 for Vaadin Framework. It seems like the old JQuery version did not contain "use strict" while the current version does contain it. 

Is there any reason to have it?

"This causes errors in several tools, e.g. phantomJs when running selenium tests, because they try to trace the stack via arguments.caller.callee, which is forbidden in the strict mode."

**Comment by jfarcand** [comment]
@Artur- Can you remove it and see if that help? I've no issue removing it.

**Comment by Corni** [comment]
Removing use strict solves the problem, but for our company this means modifying a released artifact from maven (vaadin-push.jar), which we would like to avoid ;)

So it would be great if you could remove it from atmosphere again.

**Comment by jfarcand** [comment]
@Corni It is there from day 1 so I'm a little bit afraid of making such a big change.

**Comment by Corni** [comment]
Well it hasn't been there in the old jquery JS vaadin used, has it?

This then breaks automatic GUI testing with selenium+phantomjs (a headless browser implementation, using far less ressources than firefox/chrome) for every atmosphere user :-/

**Comment by jfarcand** [comment]
@Corni Agree, but `atmosphere.js` is not the same file, it is completely rewritten without the need of jquery. atmosphere.js is there for sevral years with `strict`
