### ISSUE TITLE
Chrome cancels streaming/long-polling request when maybe navigating away

### ISSUE THREAD

**Issue by jfarcand** [Atmosphere/atmosphere-javascript#22]
Mirror of Atmosphere/atmosphere#1126

**Comment by jacobilsoe** [comment]
Is this issue fixed in 2.2.10? Or is there a workaround?

**Comment by jfarcand** [comment]
@jacobilsoe Not tested so give it a try, but No workaround or patch have been proposed. Contribution welcomed!
