### ISSUE TITLE
What is the current status of this component?

### ISSUE THREAD

**Issue by ben-crowhurst** [Atmosphere/atmosphere-javascript#222]
We implement the Atmosphere framework on a large scale project and have recently been looking to upgrade to the latest release.

We are currently having a discussion around whether moving away from Atmosphere is a better option due to the lack of active development.

Please could you clarify what is the latest frontend build and any roadmap you have in hand?

Readme states 2.3.2 is the latest yet I see 2.3.3 [mentioned](https://github.com/Atmosphere/atmosphere-javascript/releases).

**Comment by jfarcand** [comment]
Updated the page, thanks! The project is still active and we regularly release new version on demand or when a hot fix is needed.
