### ISSUE TITLE
release 2.3.3 not on Maven Central

### ISSUE THREAD

**Issue by cthiebaud** [Atmosphere/atmosphere-javascript#227]
For some reason release 2.3.3 is not on Maven Central (yet ?).

Availability on MAven central is required for [webjars](https://www.webjars.org/) packaging. 

cf. https://github.com/webjars/atmosphere-javascript/issues/7

Is there anything I could do to help releasing to Mvacen Cetral ?

thanks
Christophe

**Comment by jfarcand** [comment]
not usre why...but just released `2.3.4`

**Comment by cthiebaud** [comment]
... I do not find release 2.3.4 on Maven Central either ...

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.atmosphere.client%22%20AND%20a%3A%22javascript%22

**Comment by jfarcand** [comment]
@cthiebaud Should be there now

**Comment by cthiebaud** [comment]
Yes it it. Thanks.
