### ISSUE TITLE
TypeError: _sse.send is not a function   using Server Send Event transport

### ISSUE THREAD

**Issue by SuperPat45** [Atmosphere/atmosphere-javascript#230]
When using SSE as transport and method as 'POST', an '_sse.send is not a function' error appear in the firefox/chrome consoles on page load.

At the end of the _sse.onopen function you try to send _request.data (who is empty) to the server, as you do with websocket, but using the sse connection ?
```
_sse.onopen = function (event) {
    // ....
    if (_request.method === 'POST') {
        _response.state = "messageReceived";
        _sse.send(_request.data);
    }
}
```
The SSE spec does not logically define any send function.
You probably wanted to send using a pooling connection?

**Comment by jfarcand** [comment]
@SuperPat45 Indeed that doesn't seems right. It should use the `push` method of that script instead. Do you have the cycle to test it?

**Comment by SuperPat45** [comment]
To reproduce:
```
			var request = new atmosphere.AtmosphereRequest();
			request.url = '/ajax';
			request.closeAsync = true;
			request.method = 'POST';
			request.transport = 'sse';
			request.fallbackMethod = 'POST';
			request.fallbackTransport = 'long-polling';
                        var socket = atmosphere.subscribe(request);
```
