### ISSUE TITLE
[Discussion] Remove `JSON.stringify` / `JSON.parse` polyfill

### ISSUE THREAD

**Issue by mjeanroy** [Atmosphere/atmosphere-javascript#231]
Hi,

The `atmosphere.js` file include a polyfill for `JSON.parse` and `JSON.stringify` (see [here](https://github.com/Atmosphere/atmosphere-javascript/blob/da0f76c1655b9281ee72fffeb5a286444c69f120/modules/javascript/src/main/webapp/javascript/atmosphere.js#L3302-L3378)). Would you be open to remove it?

Here are pros/cons to remove it:
1. Reduce the file size. If someone requires a polyfill for `JSON.stringify` and `JSON.parse`, then there are a lot of chances that this polyfill is needed for other dependency of the application, there's no reason to include this polyfill more than once.
2. Avoid using `eval`. There are security reasons to avoid using `eval`, but also performance reasons : when `eval` is used, module bundlers (like rollup or webpack) and minification tools (like uglifyjs) cannot perform some optimization due to the nature of `eval`.
3. This polyfill is needed for IE7, so removing it may be a breaking change. But as I said in point 1, there are lot of chances that this polyfill is already included in this case.

What do you think?

**Comment by jfarcand** [comment]
@mjeanroy Agree...pull request welcomed!

**Comment by SuperPat45** [comment]
It would be definitely a good thing as, according to:
https://caniuse.com/#feat=json
only IE7, Firefox 3.0, Safari 3 and Opera 10 does not support it. For that case we need to add a note in the readme fill on the need to add a polyfill like:
https://github.com/bestiejs/json3
