### ISSUE TITLE
Error: "message is not defined"

### ISSUE THREAD

**Issue by nicubularda** [Atmosphere/atmosphere-javascript#266]
If setting logLevel to "warn" when the Websocket reconnect maximum try was reached you will get into the "message is not defined" error.

**Comment by jfarcand** [comment]
@nicubularda can you share the complete stack trace, and also the version used?

**Comment by tkohlman** [comment]
I see this issue in version 3.0.6 when I set `maxReconnectOnClose: 0` and then kill the server.

> Uncaught ReferenceError: message is not defined
> `at _reconnectWebSocket (atmosphere.js:1747)`
> `at WebSocket._websocket.onclose (atmosphere.js:1564)`

**Comment by ivan-lattak** [comment]
Seems to be caused by line atmosphere-3.0.6.js:1749
`atmosphere.util.warn("Websocket error, reason: " + message.reason);`
This code was probably moved here from somewhere else. The `message` variable is not defined in this scope.

**Comment by jfarcand** [comment]
@ivan-lattak Can you do a pull request? I will merge and release. Thanks

**Comment by fcorneli** [comment]
I also stumbled upon the same javascript warning when shutting down the server. Caused at:
https://github.com/Atmosphere/atmosphere-javascript/blob/2aeccb6c6afece69c664c95c7e66b3693ab8ec26/modules/javascript/src/main/webapp/javascript/atmosphere.js#L1751

**Comment by fcorneli** [comment]
Hence in 3.1.0 we have the same issue.
