### ISSUE TITLE
TypeError: Beacons can only be sent over HTTP(S)

### ISSUE THREAD

**Issue by ronnybremer** [Atmosphere/atmosphere-javascript#280]
After upgrading to Atmosphere-JS 3.1.4 I see this error in the browser log. Safari does support the Beacon API, but I am using a "websocket" transport. Is the "websocket" transport deprecated? Do I need to use long-polling or any other method?

**Comment by jfarcand** [comment]
@ronnybremer First time I see this error. Are you having it with Chrome or FF as well?

**Comment by ronnybremer** [comment]
Oh. I found the issue. Somewhere in our code the http:// was replaced with ws:// for web socket connections. Its some pretty old code. Please disregard this issue, as soon as I changed it to http:// it worked like a charm.
