### ISSUE TITLE
onReconnect is called before reconnecting

### ISSUE THREAD

**Issue by gabor-aranyossy** [Atmosphere/atmosphere-javascript#7]
Setting the flag executeCallbackBeforeReconnect to false doesn't make onReconnect handler called after successful re-connection.

**Comment by dozed** [comment]
Is this behaviour intended like this? It is a bit annoying since you dont know when the connect is open again.

**Comment by jfarcand** [comment]
`executeCallbackBeforeReconnect` is not really supported anymore, but if you have the cycle, fix it and do a pull request.

**Comment by dozed** [comment]
What is the intended behaviour of onReconnect, is it called after a connection was opened successfully or always when a new reconnect try is made?

**Comment by jfarcand** [comment]
Please use the mailing list for question: https://groups.google.com/group/atmosphere-framework?pli=1

**Comment by dozed** [comment]
You mean `executeCallbackBeforeReconnect` needs to be fixed?
